const translationEN = {
  // Navbar
  Nap: "Nap",
  Up: "Up",
  Down: "Down",
  Mute: "Mute",
  Settings: "Settings",
  "Log Out": "Log Out",
  Back: "Back",

  // Sidebar
  Dashboard: "Dashboard",
  Feed: "Feed",
  Brands: "Brands",
  Influencers: "Influencers",
  Categories: "Categories",
  Ads: "Ads",
  Posts: "Posts",
  "My Profile": "My Profile",
  "Account Settings": "Account Settings",

  // Nap Screen
  "This screen will disappear after:": "This screen will disappear after:",

  // Login
  "Sign in": "Sign in",
  "Successfully signed in!": "Successfully signed in!",
  "Something went wrong!": "Something went wrong!",
  "Sign in to your Osher account": "Sign in to your Osher account",
  "Email Address": "Email Address",
  Password: "Password",
  "Forgot your password?": "Forgot your password?",
  "Enter your email": "Enter your email",
  "Enter your password": "Enter your password",

  // Dashboard
  "My Ads": "My Ads",
  "My Posts": "My Posts",
  "Welcome back": "Welcome back",
  "Let's check your stats!": "Let's check your stats!",

  // Table Block
  "No data present": "No data present",
  "Search here": "Search here",

  // Table Headers
  ID: "ID",
  Name: "Name",
  "Email address": "Email address",

  // Brands
  "These are all the brands": "These are all the brands",
  "Add Brand": "Add Brand",
  "There are no brands present. Please add a brand.":
    "There are no brands present. Please add a brand.",
  Brand: "Brand",
  Address: "Address",
  Phone: "Phone",
  "Edit Brand": "Edit Brand",
  "Ads of": "Ads of",
  "These are all the Ads of": "These are all the Ads of",
  "There are no ads generated by": "There are no ads generated by",

  // Influencer
  "These are all the influencers": "These are all the influencers",
  "Add Influencer": "Add Influencer",
  "There are no influencers present. Please add an influencer.":
    "There are no influencers present. Please add an influencer.",
  Influencer: "Influencer",
  "Edit Influencer": "Edit Influencer",
  "Posts of": "Posts of",
  "These are all the posts of": "These are all the posts of",
  "There are no posts by": "There are no posts by",

  // Categories
  Category: "Category",
  "These are all the categories": "These are all the categories",
  "There are no categories present.": "There are no categories present.",

  // Ads
  "These are all the ads": "These are all the ads",
  "Add ad": "Add ad",
  "There are no ads present. Please add an ad.":
    "There are no ads present. Please add an ad.",
  Ad: "Ad",
  "Publish Date": "Publish Date",
  "Expiry Date": "Expiry Date",
  "Edit Ad": "Edit Ad",

  // Posts
  "These are all the posts": "These are all the posts",
  "Add post": "Add post",
  "There are no posts present. Please add a post.":
    "There are no posts present. Please add a post.",
  Post: "Post",
  Description: "Description",
  "Edit Post": "Edit Post",

  // DeleteDialog
  "Are you sure you want to delete ": "Are you sure you want to delete ",
  "the account of": "the account of",

  // My Profile
  My: "My",
  ads: "ads",
  posts: "posts",
  "These are all my": "These are all my",
  "There are no": "There are no",
  "by me": "by me",
  "You cannot delete brands those have generated ads":
    "You cannot delete brands those have generated ads",

  // Account Settings
  "Update your photo and personal details":
    "Update your photo and personal details",
  "Your Photo": "Your Photo",
  "This will be displayed on your profile":
    "This will be displayed on your profile",
  "@example": "@example",
  "New Password": "New Password",

  // Common
  Admin: "Admin",
  Edit: "Edit",
  Delete: "Delete",
  Cancel: "Cancel",
  Continue: "Continue",
  Email: "Email",
  "Phone Number": "Phone Number",
  "Save Changes": "Save Changes",

  // Image Uploader
  "The selected image exceeds the maximum allowed size. Please choose a smaller image file.":
    "The selected image exceeds the maximum allowed size. Please choose a smaller image file.",

  // Form Errors
  "Name cannot be empty": "Name cannot be empty",
  "New password should be different": "New password should be different",
  "New password cannot be empty": "New password cannot be empty",
  "Password length must be at least 5 characters":
    "Password length must be at least 5 characters",
  "Password cannot be empty": "Password cannot be empty",
  "Enter a valid email": "Enter a valid email",
  "Email cannot be empty": "Email cannot be empty",

  // API Errors
  "Incorrect current password": "Incorrect current password",
  "A user with this email already exists":
    "A user with this email already exists",

  // Toast Messages
  "Profile updated successfully!": "Profile updated successfully!",
};

export { translationEN };
