const translationEN = {
  // Navbar
  Nap: "Nap",
  Up: "Up",
  Down: "Down",
  Mute: "Mute",
  Brightness: "Brightness",
  Settings: "Settings",
  "Log Out": "Log Out",
  Back: "Back",

  // Sidebar
  Dashboard: "Dashboard",
  Feed: "Feed",
  Brands: "Brands",
  Influencers: "Influencers",
  Categories: "Categories",
  Ads: "Ads",
  Posts: "Posts",
  "My Profile": "My Profile",
  "Account Settings": "Account Settings",

  // Nap Screen
  "This screen will disappear after:": "This screen will disappear after:",

  // Login
  "Sign in": "Sign in",
  "Successfully signed in!": "Successfully signed in!",
  "Something went wrong!": "Something went wrong!",
  "Sign in to your Osher account": "Sign in to your Osher account",
  "Email Address": "Email Address",
  Password: "Password",
  "Forgot your password?": "Forgot your password?",
  "Enter your email": "Enter your email",
  "Enter your password": "Enter your password",

  // Forgot Password Dialog
  "User with given email doesn't exist": "User with given email doesn't exist",
  "Email address not found in our records":
    "Email address not found in our records",
  "Check your email": "Check your email",
  "Forgot password?": "Forgot password?",
  "We've sent you a password reset link":
    "We've sent you a password reset link",
  "No worries we’ll send you reset instructions":
    "No worries we’ll send you reset instructions",
  "Open email app": "Open email app",
  "Send Now": "Send Now",
  "Didn’t receive the email? ": "Didn’t receive the email? ",
  "Remember your password? ": "Remember your password? ",
  "Click to resend": "Click to resend",

  // Home Page
  "PLAY GAMES AND WIN PRIZES": "PLAY GAMES AND WIN PRIZES",
  "SEE THE BEST SPOTS AROUND YOU": "SEE THE BEST SPOTS AROUND YOU",
  FEED: "FEED",
  "Explore Spots coming soon...": "Explore Spots coming soon...",
  "Games coming soon...": "Games coming soon...",

  // Games
  Question: "Question",
  of: "of",
  Next: "Next",
  Finish: "Finish",
  "🎉 Game Over!": "🎉 Game Over!",
  "You scored": "You scored",
  "out of": "out of",
  "Play Again": "Play Again",
  "What is the capital of France?": "What is the capital of France?",
  "Which planet is known as the Red Planet?":
    "Which planet is known as the Red Planet?",
  "What is the largest ocean on Earth?": "What is the largest ocean on Earth?",
  "Which animal is the largest land mammal?":
    "Which animal is the largest land mammal?",
  "Which sport is known as the 'king of sports'?":
    "Which sport is known as the 'king of sports'?",
  Paris: "Paris",
  Rome: "Rome",
  Madrid: "Madrid",
  Berlin: "Berlin",
  Earth: "Earth",
  Mars: "Mars",
  Jupiter: "Jupiter",
  Saturn: "Saturn",
  Atlantic: "Atlantic",
  Indian: "Indian",
  Pacific: "Pacific",
  Arctic: "Arctic",
  Elephant: "Elephant",
  Rhino: "Rhino",
  Hippo: "Hippo",
  Giraffe: "Giraffe",
  Cricket: "Cricket",
  Basketball: "Basketball",
  Football: "Football",
  Tennis: "Tennis",

  // 404 Not Found Page
  "Page not found!": "Page not found!",
  "Back to": "Back to",
  Home: "Home",
  "Back to Home": "Back to Home",
  "Back to Dashboard": "Back to Dashboard",

  // Dashboard
  "My Ads": "My Ads",
  "My Posts": "My Posts",
  "Welcome back": "Welcome back",
  "Let's check your stats!": "Let's check your stats!",

  // Feed
  "AD will be displayed here": "AD will be displayed here",

  // Table Block
  "No data present": "No data present",
  "Search here": "Search here",

  // Table Headers
  ID: "ID",
  Name: "Name",
  "Email address": "Email address",

  // Brands
  "These are all the brands": "These are all the brands",
  "Add Brand": "Add Brand",
  "There are no brands present. Please add a brand.":
    "There are no brands present. Please add a brand.",
  Brand: "Brand",
  Address: "Address",
  Phone: "Phone",
  "Edit Brand": "Edit Brand",
  "Ads of": "Ads of",
  "These are all the Ads of": "These are all the Ads of",
  "There are no ads generated by": "There are no ads generated by",
  "Brand Photo": "Brand Photo",
  "This will be displayed on the profile of Brand":
    "This will be displayed on the profile of Brand",
  "Edit the details of Brand": "Edit the details of Brand",
  "Please provide the details to add a new brand":
    "Please provide the details to add a new brand",
  "Add new Brand": "Add new Brand",

  // Influencers
  "These are all the influencers": "These are all the influencers",
  "Add Influencer": "Add Influencer",
  "There are no influencers present. Please add an influencer.":
    "There are no influencers present. Please add an influencer.",
  Influencer: "Influencer",
  "Edit Influencer": "Edit Influencer",
  "Posts of": "Posts of",
  "These are all the posts of": "These are all the posts of",
  "There are no posts by": "There are no posts by",
  "Influencer Photo": "Influencer Photo",
  "This will be displayed on the profile of Influencer":
    "This will be displayed on the profile of Influencer",
  "Edit the details of Influencer": "Edit the details of Influencer",
  "Please provide the details to add a new influencer":
    "Please provide the details to add a new influencer",
  "Add new Influencer": "Add new Influencer",

  // Categories
  Category: "Category",
  "These are all the categories": "These are all the categories",
  "There are no categories present.": "There are no categories present.",

  // Ads
  "These are all the ads": "These are all the ads",
  "Add ad": "Add ad",
  "There are no ads present. Please add an ad.":
    "There are no ads present. Please add an ad.",
  Ad: "Ad",
  "Publish Date": "Publish Date",
  "Expiry Date": "Expiry Date",
  "Edit Ad": "Edit Ad",
  "You are not allowed to edit this ad": "You are not allowed to edit this ad",
  "Ad Photo": "Ad Photo",
  "This will be displayed on the profile of Ad":
    "This will be displayed on the profile of Ad",
  "Select Brand": "Select Brand",
  "Select Category": "Select Category",
  "Edit the details of Ad": "Edit the details of Ad",
  "Add new Ad": "Add new Ad",
  "Time Slots": "Time Slots",
  Days: "Days",
  States: "States",
  "Select time slots": "Select time slots",
  "Select days": "Select days",
  "Select states": "Select states",
  "Time slots cannot be empty": "Time slots cannot be empty",
  "States cannot be empty": "States cannot be empty",
  "Days cannot be empty": "Days cannot be empty",

  // Posts
  "These are all the posts": "These are all the posts",
  "Add post": "Add post",
  "There are no posts present. Please add a post.":
    "There are no posts present. Please add a post.",
  Post: "Post",
  Description: "Description",
  "Edit Post": "Edit Post",
  "Edit the details of Post": "Edit the details of Post",
  "Select Influencer": "Select Influencer",
  "This will be the photo of post": "This will be the photo of post",
  "Post Photo": "Post Photo",
  "Add new Post": "Add new Post",
  "Please provide the details to add a new Post":
    "Please provide the details to add a new Post",

  // DeleteDialog
  "Are you sure you want to delete ": "Are you sure you want to delete ",
  "the account of": "the account of",

  // My Profile
  My: "My",
  ads: "ads",
  posts: "posts",
  "These are all my": "These are all my",
  "There are no": "There are no",
  "by me": "by me",
  "You cannot delete brands those have generated ads":
    "You cannot delete brands those have generated ads",

  // Account Settings
  "Update your photo and personal details":
    "Update your photo and personal details",
  "Your Photo": "Your Photo",
  "This will be displayed on your profile":
    "This will be displayed on your profile",
  "@example": "@example",
  "New Password": "New Password",

  // OTP Dialog
  "Verify Your Email": "Verify Your Email",
  "Please check your inbox for a verification code to update your email":
    "Please check your inbox for a verification code to update your email",

  // Common
  Admin: "Admin",
  Edit: "Edit",
  Delete: "Delete",
  Cancel: "Cancel",
  Continue: "Continue",
  Email: "Email",
  "Phone Number": "Phone Number",
  "Save Changes": "Save Changes",
  "Confirm Password": "Confirm Password",
  Verify: "Verify",
  "Toggle password visibility": "Toggle password visibility",
  "Not given": "Not given",
  "Select All": "Select All",
  "Unselect All": "Unselect All",

  // Image Uploader
  "The selected image exceeds the maximum allowed size. Please choose a smaller image file.":
    "The selected image exceeds the maximum allowed size. Please choose a smaller image file.",

  // Form Errors
  "Name cannot be empty": "Name cannot be empty",
  "New password should be different": "New password should be different",
  "New password cannot be empty": "New password cannot be empty",
  "Confirm Password cannot be empty": "Confirm Password cannot be empty",
  "Password length must be at least 5 characters":
    "Password length must be at least 5 characters",
  "Password cannot be empty": "Password cannot be empty",
  "Enter a valid email": "Enter a valid email",
  "Email cannot be empty": "Email cannot be empty",
  "Picture cannot be empty": "Picture cannot be empty",
  "Description cannot be empty": "Description cannot be empty",
  "Influencer cannot be empty": "Influencer cannot be empty",
  "Brand cannot be empty": "Brand cannot be empty",
  "Category cannot be empty": "Category cannot be empty",
  "Address cannot be empty": "Address cannot be empty",
  "Phone Number cannot be empty": "Phone Number cannot be empty",
  "An influencer with this email already exists":
    "An influencer with this email already exists",
  "An Ad with this name already exists": "An Ad with this name already exists",
  "Please provide the details to add a new Ad":
    "Please provide the details to add a new Ad",
  "Passwords do not match": "Passwords do not match",
  "Please enter complete otp code": "Please enter complete otp code",
  "Otp cannot be empty": "Otp cannot be empty",

  // API Errors
  "Incorrect current password": "Incorrect current password",
  "A user with this email already exists":
    "A user with this email already exists",
  "A brand with this email already exists":
    "A brand with this email already exists",
  "Failed to fetch brands": "Failed to fetch brands",
  "You are not allowed to edit this post":
    "You are not allowed to edit this post",
  "Failed to fetch influencers": "Failed to fetch influencers",
  "User with this email doesn't exists": "User with this email doesn't exists",
  "Invalid email or password": "Invalid email or password",
  "Email is missing": "Email is missing",
  "Name is missing": "Name is missing",
  "Password is missing": "Password is missing",
  "New Password is missing": "New Password is missing",
  "The user with the given email was not found.":
    "The user with the given email was not found.",
  "Invalid brand id": "Invalid brand id",
  "Brand with the given id was not found":
    "Brand with the given id was not found",
  "Phone is missing": "Phone is missing",
  "Address is missing": "Address is missing",
  "Brand Id is missing": "Brand Id is missing",
  "New password is missing": "New password is missing",
  "Brand with the given email was not found.":
    "Brand with the given email was not found.",
  "Invalid influencer id": "Invalid influencer id",
  "Influencer with the given id was not found":
    "Influencer with the given id was not found",
  "Influencer Id is missing": "Influencer Id is missing",
  "Influencer with the given email was not found.":
    "Influencer with the given email was not found.",
  "This ad is not available": "This ad is not available",
  "Ad with the given id was not found": "Ad with the given id was not found",
  "Description is missing": "Description is missing",
  "Category is not selected": "Category is not selected",
  "Brand is not selected": "Brand is not selected",
  "Invalid brandId": "Invalid brandId",
  "Invalid categoryId": "Invalid categoryId",
  "Brand not found": "Brand not found",
  "Category not found": "Category not found",
  "Ad with the given id was not found.": "Ad with the given id was not found.",
  "This post is not available": "This post is not available",
  "Post with the given id was not found":
    "Post with the given id was not found",
  "User is not selected": "User is not selected",
  "Picture is missing": "Picture is missing",
  "Invalid userId": "Invalid userId",
  "User not found": "User not found",
  "Post with the given id was not found.":
    "Post with the given id was not found.",

  // Toast Messages
  "Profile updated successfully!": "Profile updated successfully!",
  "Post updated successfully!": "Post updated successfully!",
  "Ad updated successfully!": "Ad updated successfully!",
  "Brand updated successfully!": "Brand updated successfully!",
  "Influencer updated successfully!": "Influencer updated successfully!",
  "Brand deleted successfully!": "Brand deleted successfully!",
  "Ad deleted successfully!": "Ad deleted successfully!",
  "Post deleted successfully!": "Post deleted successfully!",
  "Influencer deleted successfully!": "Influencer deleted successfully!",
  "Ad added successfully!": "Ad added successfully!",
  "Post added successfully!": "Post added successfully!",
  "Brand added successfully!": "Brand added successfully!",
  "Influencer added successfully!": "Influencer added successfully!",
  "Your email has been verified!": "Your email has been verified!",
  "Please enter the correct OTP code": "Please enter the correct OTP code",
  "Password reset link has been sent!": "Password reset link has been sent!",
};

export { translationEN };
