const translationFR = {
  // Navbar
  Nap: "Sieste",
  Up: "Haut",
  Down: "Bas",
  Mute: "Muet",
  Brightness: "Luminosité",
  Settings: "Paramètres",
  "Log Out": "Se déconnecter",
  Back: "Retour",

  // Sidebar
  Dashboard: "Tableau de bord",
  Feed: "Fil d’actualités",
  Brands: "Marques",
  Influencers: "Influenceurs",
  Categories: "Catégories",
  Ads: "Publicités",
  Posts: "Publications",
  "My Profile": "Mon profil",
  "Account Settings": "Paramètres du compte",

  // Nap Screen
  "This screen will disappear after:": "Cet écran disparaîtra après :",

  // Login
  "Sign in": "Se connecter",
  "Successfully signed in!": "Connexion réussie !",
  "Something went wrong!": "Une erreur s’est produite !",
  "Sign in to your Osher account": "Connectez-vous à votre compte Osher",
  "Email Address": "Adresse e-mail",
  Password: "Mot de passe",
  "Forgot your password?": "Mot de passe oublié ?",
  "Enter your email": "Entrez votre e-mail",
  "Enter your password": "Entrez votre mot de passe",

  // Forgot Password Dialog
  "User with given email doesn't exist": "Aucun utilisateur avec cet e-mail",
  "Email address not found in our records":
    "Adresse e-mail introuvable dans nos dossiers",
  "Check your email": "Vérifiez votre e-mail",
  "Forgot password?": "Mot de passe oublié ?",
  "We've sent you a password reset link":
    "Nous vous avons envoyé un lien de réinitialisation",
  "No worries we’ll send you reset instructions":
    "Pas de souci, nous allons vous envoyer les instructions",
  "Open email app": "Ouvrir l’application mail",
  "Send Now": "Envoyer maintenant",
  "Didn’t receive the email? ": "Vous n’avez pas reçu l’e-mail ? ",
  "Remember your password? ": "Vous vous souvenez de votre mot de passe ? ",
  "Click to resend": "Cliquez pour renvoyer",

  // Home Page
  "PLAY GAMES AND WIN PRIZES": "JOUEZ À DES JEUX ET GAGNEZ DES PRIX",
  "SEE THE BEST SPOTS AROUND YOU":
    "VOYEZ LES MEILLEURS ENDROITS AUTOUR DE VOUS",
  FEED: "FIL",
  "Games coming soon...": "Jeux à venir...",
  "Explore Spots coming soon...": "Explorer les endroits à venir...",

  // Games
  Question: "Question",
  of: "de",
  Next: "Suivant",
  Finish: "Terminer",
  "🎉 Game Over!": "🎉 Fin du jeu !",
  "You scored": "Vous avez marqué",
  "out of": "sur",
  "Play Again": "Rejouer",
  "What is the capital of France?": "Quelle est la capitale de la France ?",
  "Which planet is known as the Red Planet?":
    "Quelle planète est connue comme la planète rouge ?",
  "What is the largest ocean on Earth?":
    "Quel est le plus grand océan sur Terre ?",
  "Which animal is the largest land mammal?":
    "Quel animal est le plus grand mammifère terrestre ?",
  "Which sport is known as the 'king of sports'?":
    "Quel sport est connu comme le 'roi des sports' ?",
  Paris: "Paris",
  Rome: "Rome",
  Madrid: "Madrid",
  Berlin: "Berlin",
  Earth: "Terre",
  Mars: "Mars",
  Jupiter: "Jupiter",
  Saturn: "Saturne",
  Atlantic: "Atlantique",
  Indian: "Indien",
  Pacific: "Pacifique",
  Arctic: "Arctique",
  Elephant: "Éléphant",
  Rhino: "Rhinocéros",
  Hippo: "Hippopotame",
  Giraffe: "Girafe",
  Cricket: "Cricket",
  Basketball: "Basket-ball",
  Football: "Football",
  Tennis: "Tennis",

  // 404 Not Found Page
  "Page not found!": "Page non trouvée !",
  "Back to": "Retour à",
  Home: "Accueil",
  "Back to Home": "Retour à l’accueil",
  "Back to Dashboard": "Retour au tableau de bord",

  // Dashboard
  "My Ads": "Mes publicités",
  "My Posts": "Mes publications",
  "Welcome back": "Bon retour",
  "Let's check your stats!": "Voyons vos statistiques !",

  // Feed
  "AD will be displayed here": "La publicité sera affichée ici",

  // Table Block
  "No data present": "Aucune donnée disponible",
  "Search here": "Rechercher ici",

  // Table Headers
  ID: "ID",
  Name: "Nom",
  "Email address": "Adresse e-mail",

  // Brands
  "These are all the brands": "Voici toutes les marques",
  "Add Brand": "Ajouter une marque",
  "There are no brands present. Please add a brand.":
    "Aucune marque présente. Veuillez en ajouter une.",
  Brand: "Marque",
  Address: "Adresse",
  Phone: "Téléphone",
  "Edit Brand": "Modifier la marque",
  "Ads of": "Publicités de",
  "These are all the Ads of": "Voici toutes les publicités de",
  "There are no ads generated by": "Aucune publicité générée par",
  "Brand Photo": "Photo de la marque",
  "This will be displayed on the profile of Brand":
    "Ceci sera affiché sur le profil de la marque",
  "Edit the details of Brand": "Modifier les détails de la marque",
  "Please provide the details to add a new brand":
    "Veuillez fournir les détails pour ajouter une nouvelle marque",
  "Add new Brand": "Ajouter une nouvelle marque",

  // Influencers
  "These are all the influencers": "Voici tous les influenceurs",
  "Add Influencer": "Ajouter un influenceur",
  "There are no influencers present. Please add an influencer.":
    "Aucun influenceur n'est présent. Veuillez en ajouter un.",
  Influencer: "Influenceur",
  "Edit Influencer": "Modifier l'influenceur",
  "Posts of": "Publications de",
  "These are all the posts of": "Voici toutes les publications de",
  "There are no posts by": "Il n'y a aucune publication de",
  "Influencer Photo": "Photo de l'influenceur",
  "This will be displayed on the profile of Influencer":
    "Ceci sera affiché sur le profil de l'influenceur",
  "Edit the details of Influencer": "Modifier les détails de l'influenceur",
  "Please provide the details to add a new influencer":
    "Veuillez fournir les détails pour ajouter un nouvel influenceur",
  "Add new Influencer": "Ajouter un nouvel influenceur",

  // Categories
  Category: "Catégorie",
  "These are all the categories": "Voici toutes les catégories",
  "There are no categories present.": "Aucune catégorie n'est présente.",

  // Ads
  "These are all the ads": "Voici toutes les annonces",
  "Add ad": "Ajouter une annonce",
  "There are no ads present. Please add an ad.":
    "Aucune annonce n'est présente. Veuillez en ajouter une.",
  Ad: "Annonce",
  "Publish Date": "Date de publication",
  "Expiry Date": "Date d'expiration",
  "Edit Ad": "Modifier l'annonce",
  "You are not allowed to edit this ad":
    "Vous n'êtes pas autorisé à modifier cette annonce",
  "Ad Photo": "Photo de l'annonce",
  "This will be displayed on the profile of Ad":
    "Ceci sera affiché sur le profil de l'annonce",
  "Select Brand": "Sélectionner une marque",
  "Select Category": "Sélectionner une catégorie",
  "Edit the details of Ad": "Modifier les détails de l'annonce",
  "Add new Ad": "Ajouter une nouvelle annonce",

  // Posts
  "These are all the posts": "Voici toutes les publications",
  "Add post": "Ajouter une publication",
  "There are no posts present. Please add a post.":
    "Aucune publication n'est présente. Veuillez en ajouter une.",
  Post: "Publication",
  Description: "Description",
  "Edit Post": "Modifier la publication",
  "Edit the details of Post": "Modifier les détails de la publication",
  "Select Influencer": "Sélectionner un influenceur",
  "This will be the photo of post": "Ceci sera la photo de la publication",
  "Post Photo": "Photo de la publication",
  "Add new Post": "Ajouter une nouvelle publication",
  "Please provide the details to add a new Post":
    "Veuillez fournir les détails pour ajouter une nouvelle publication",

  // DeleteDialog
  "Are you sure you want to delete ": "Êtes-vous sûr de vouloir supprimer ",
  "the account of": "le compte de",

  // My Profile
  My: "Mes",
  ads: "annonces",
  posts: "publications",
  "These are all my": "Voici tous mes",
  "There are no": "Il n'y a aucun",
  "by me": "par moi",
  "You cannot delete brands those have generated ads":
    "Vous ne pouvez pas supprimer des marques ayant généré des annonces",

  // Account Settings
  "Update your photo and personal details":
    "Mettez à jour votre photo et vos informations personnelles",
  "Your Photo": "Votre photo",
  "This will be displayed on your profile":
    "Ceci sera affiché sur votre profil",
  "@example": "@exemple",
  "New Password": "Nouveau mot de passe",

  // OTP Dialog
  "Verify Your Email": "Vérifiez votre e-mail",
  "Please check your inbox for a verification code to update your email":
    "Veuillez vérifier votre boîte de réception pour un code de vérification afin de mettre à jour votre e-mail",

  // Common
  Admin: "Admin",
  Edit: "Modifier",
  Delete: "Supprimer",
  Cancel: "Annuler",
  Continue: "Continuer",
  Email: "E-mail",
  "Phone Number": "Numéro de téléphone",
  "Save Changes": "Enregistrer les modifications",
  "Confirm Password": "Confirmer le mot de passe",
  Verify: "Vérifier",
  "Toggle password visibility": "Afficher/masquer le mot de passe",

  // Image Uploader
  "The selected image exceeds the maximum allowed size. Please choose a smaller image file.":
    "L'image sélectionnée dépasse la taille maximale autorisée. Veuillez choisir un fichier image plus petit.",

  // Form Errors
  "Name cannot be empty": "Le nom ne peut pas être vide",
  "New password should be different":
    "Le nouveau mot de passe doit être différent",
  "New password cannot be empty":
    "Le nouveau mot de passe ne peut pas être vide",
  "Confirm Password cannot be empty":
    "Le mot de passe de confirmation ne peut pas être vide",
  "Password length must be at least 5 characters":
    "Le mot de passe doit contenir au moins 5 caractères",
  "Password cannot be empty": "Le mot de passe ne peut pas être vide",
  "Enter a valid email": "Entrez une adresse e-mail valide",
  "Email cannot be empty": "L'e-mail ne peut pas être vide",
  "Picture cannot be empty": "L'image ne peut pas être vide",
  "Description cannot be empty": "La description ne peut pas être vide",
  "Influencer cannot be empty": "L'influenceur ne peut pas être vide",
  "Brand cannot be empty": "La marque ne peut pas être vide",
  "Category cannot be empty": "La catégorie ne peut pas être vide",
  "Address cannot be empty": "L'adresse ne peut pas être vide",
  "Phone Number cannot be empty":
    "Le numéro de téléphone ne peut pas être vide",
  "An influencer with this email already exists":
    "Un influenceur avec cet e-mail existe déjà",
  "An Ad with this name already exists": "Une annonce avec ce nom existe déjà",
  "Please provide the details to add a new Ad":
    "Veuillez fournir les détails pour ajouter une nouvelle annonce",
  "Passwords do not match": "Les mots de passe ne correspondent pas",
  "Please enter complete otp code": "Veuillez entrer le code OTP complet",
  "Otp cannot be empty": "Le code OTP ne peut pas être vide",

  // API Errors
  "Incorrect current password": "Mot de passe actuel incorrect",
  "A user with this email already exists":
    "Un utilisateur avec cet e-mail existe déjà",
  "A brand with this email already exists":
    "Une marque avec cet e-mail existe déjà",
  "Failed to fetch brands": "Échec de la récupération des marques",
  "You are not allowed to edit this post":
    "Vous n'êtes pas autorisé à modifier cette publication",
  "Failed to fetch influencers": "Échec de la récupération des influenceurs",
  "User with this email doesn't exists": "Aucun utilisateur avec cet e-mail",
  "Invalid email or password": "E-mail ou mot de passe invalide",
  "Email is missing": "L'e-mail est manquant",
  "Name is missing": "Le nom est manquant",
  "Password is missing": "Le mot de passe est manquant",
  "New Password is missing": "Le nouveau mot de passe est manquant",
  "The user with the given email was not found.":
    "L'utilisateur avec cet e-mail n'a pas été trouvé.",
  "Invalid brand id": "Identifiant de marque invalide",
  "Brand with the given id was not found":
    "Aucune marque trouvée avec cet identifiant",
  "Phone is missing": "Le numéro de téléphone est manquant",
  "Address is missing": "L'adresse est manquante",
  "Brand Id is missing": "L'identifiant de la marque est manquant",
  "New password is missing": "Le nouveau mot de passe est manquant",
  "Brand with the given email was not found.":
    "Aucune marque trouvée avec cet e-mail.",
  "Invalid influencer id": "Identifiant d'influenceur invalide",
  "Influencer with the given id was not found":
    "Aucun influenceur trouvé avec cet identifiant",
  "Influencer Id is missing": "L'identifiant de l'influenceur est manquant",
  "Influencer with the given email was not found.":
    "Aucun influenceur trouvé avec cet e-mail.",
  "This ad is not available": "Cette annonce n'est pas disponible",
  "Ad with the given id was not found":
    "Aucune annonce trouvée avec cet identifiant",
  "Description is missing": "La description est manquante",
  "Category is not selected": "Aucune catégorie sélectionnée",
  "Brand is not selected": "Aucune marque sélectionnée",
  "Invalid brandId": "Identifiant de marque invalide",
  "Invalid categoryId": "Identifiant de catégorie invalide",
  "Brand not found": "Marque non trouvée",
  "Category not found": "Catégorie non trouvée",
  "Ad with the given id was not found.":
    "Aucune annonce trouvée avec cet identifiant.",
  "This post is not available": "Cette publication n'est pas disponible",
  "Post with the given id was not found":
    "Aucune publication trouvée avec cet identifiant",
  "User is not selected": "Aucun utilisateur sélectionné",
  "Picture is missing": "L'image est manquante",
  "Invalid userId": "Identifiant utilisateur invalide",
  "User not found": "Utilisateur non trouvé",
  "Post with the given id was not found.":
    "Aucune publication trouvée avec cet identifiant.",

  // Toast Messages
  "Profile updated successfully!": "Profil mis à jour avec succès !",
  "Post updated successfully!": "Publication mise à jour avec succès !",
  "Ad updated successfully!": "Annonce mise à jour avec succès !",
  "Brand updated successfully!": "Marque mise à jour avec succès !",
  "Influencer updated successfully!": "Influenceur mis à jour avec succès !",
  "Brand deleted successfully!": "Marque supprimée avec succès !",
  "Ad deleted successfully!": "Annonce supprimée avec succès !",
  "Post deleted successfully!": "Publication supprimée avec succès !",
  "Influencer deleted successfully!": "Influenceur supprimé avec succès !",
  "Ad added successfully!": "Annonce ajoutée avec succès !",
  "Post added successfully!": "Publication ajoutée avec succès !",
  "Brand added successfully!": "Marque ajoutée avec succès !",
  "Influencer added successfully!": "Influenceur ajouté avec succès !",
  "Your email has been verified!": "Votre e-mail a été vérifié !",
  "Please enter the correct OTP code": "Veuillez entrer le bon code OTP",
  "Password reset link has been sent!":
    "Le lien de réinitialisation du mot de passe a été envoyé !",
};

export { translationFR };
