const translationFR = {
  // Navbar
  Nap: "Sieste",
  Up: "Haut",
  Down: "Bas",
  Mute: "Muet",
  Settings: "Paramètres",
  "Log Out": "Se déconnecter",
  Back: "Retour",

  // Sidebar
  Dashboard: "Tableau de bord",
  Feed: "Fil d'actualité",
  Brands: "Marques",
  Influencers: "Influenceurs",
  Categories: "Catégories",
  Ads: "Annonces",
  Posts: "Publications",
  "My Profile": "Mon profil",
  "Account Settings": "Paramètres du compte",

  // Nap Screen
  "This screen will disappear after:": "Cet écran disparaîtra après :",

  // Login
  "Sign in": "Se connecter",
  "Successfully signed in!": "Connexion réussie !",
  "Something went wrong!": "Une erreur s'est produite !",
  "Sign in to your Osher account": "Connectez-vous à votre compte Osher",
  "Email Address": "Adresse e-mail",
  Password: "Mot de passe",
  "Forgot your password?": "Mot de passe oublié ?",
  "Enter your email": "Entrez votre e-mail",
  "Enter your password": "Entrez votre mot de passe",

  // Dashboard
  "My Ads": "Mes annonces",
  "My Posts": "Mes publications",
  "Welcome back": "Bon retour",
  "Let's check your stats!": "Voyons vos statistiques !",

  // Table Block
  "No data present": "Aucune donnée disponible",
  "Search here": "Rechercher ici",

  // Table Headers
  ID: "ID",
  Name: "Nom",
  "Email address": "Adresse e-mail",

  // Brands
  "These are all the brands": "Voici toutes les marques",
  "Add Brand": "Ajouter une marque",
  "There are no brands present. Please add a brand.":
    "Aucune marque présente. Veuillez ajouter une marque.",
  Brand: "Marque",
  Address: "Adresse",
  Phone: "Téléphone",
  "Edit Brand": "Modifier la marque",
  "Ads of": "Annonces de",
  "These are all the Ads of": "Voici toutes les annonces de",
  "There are no ads generated by": "Aucune annonce générée par",

  // Influencer
  "These are all the influencers": "Voici tous les influenceurs",
  "Add Influencer": "Ajouter un influenceur",
  "There are no influencers present. Please add an influencer.":
    "Aucun influenceur présent. Veuillez en ajouter un.",
  Influencer: "Influenceur",
  "Edit Influencer": "Modifier l'influenceur",
  "Posts of": "Publications de",
  "These are all the posts of": "Voici toutes les publications de",
  "There are no posts by": "Aucune publication de",

  // Categories
  Category: "Catégorie",
  "These are all the categories": "Voici toutes les catégories",
  "There are no categories present.": "Aucune catégorie présente.",

  // Ads
  "These are all the ads": "Voici toutes les annonces",
  "Add ad": "Ajouter une annonce",
  "There are no ads present. Please add an ad.":
    "Aucune annonce présente. Veuillez en ajouter une.",
  Ad: "Annonce",
  "Publish Date": "Date de publication",
  "Expiry Date": "Date d'expiration",
  "Edit Ad": "Modifier l'annonce",

  // Posts
  "These are all the posts": "Voici toutes les publications",
  "Add post": "Ajouter une publication",
  "There are no posts present. Please add a post.":
    "Aucune publication présente. Veuillez en ajouter une.",
  Post: "Publication",
  Description: "Description",
  "Edit Post": "Modifier la publication",

  // DeleteDialog
  "Are you sure you want to delete ": "Êtes-vous sûr de vouloir supprimer ",
  "the account of": "le compte de",

  // My Profile
  My: "Mes",
  ads: "annonces",
  posts: "publications",
  "These are all my": "Voici toutes mes",
  "There are no": "Il n'y a pas de",
  "by me": "par moi",
  "You cannot delete brands those have generated ads":
    "Vous ne pouvez pas supprimer les marques ayant généré des annonces",

  // Account Settings
  "Update your photo and personal details":
    "Mettez à jour votre photo et vos informations personnelles",
  "Your Photo": "Votre photo",
  "This will be displayed on your profile":
    "Ceci sera affiché sur votre profil",
  "@example": "@exemple",
  "New Password": "Nouveau mot de passe",

  // Common
  Admin: "Admin",
  Edit: "Modifier",
  Delete: "Supprimer",
  Cancel: "Annuler",
  Continue: "Continuer",
  Email: "E-mail",
  "Phone Number": "Numéro de téléphone",
  "Save Changes": "Enregistrer les modifications",

  // Image Uploader
  "The selected image exceeds the maximum allowed size. Please choose a smaller image file.":
    "L’image sélectionnée dépasse la taille maximale autorisée. Veuillez choisir un fichier image plus petit.",

  // Form Errors
  "Name cannot be empty": "Le nom ne peut pas être vide",
  "New password should be different":
    "Le nouveau mot de passe doit être différent",
  "New password cannot be empty":
    "Le nouveau mot de passe ne peut pas être vide",
  "Password length must be at least 5 characters":
    "Le mot de passe doit contenir au moins 5 caractères",
  "Password cannot be empty": "Le mot de passe ne peut pas être vide",
  "Enter a valid email": "Entrez un e-mail valide",
  "Email cannot be empty": "L'e-mail ne peut pas être vide",

  // API Errors
  "Incorrect current password": "Mot de passe actuel incorrect",
  "A user with this email already exists":
    "Un utilisateur avec cet e-mail existe déjà",

  // Toast Messages
  "Profile updated successfully!": "Profil mis à jour avec succès !",
};

export { translationFR };
