import { useNavigate, useParams } from "react-router-dom";
import PageLayout from "../PageLayout/PageLayout";
import { useEffect, useState } from "react";
import { allRoutes } from "../../Routes/AllRoutes";
import DeleteDialog from "../Customers/DeleteDialog";
import ProfileHeader from "../Admins/ProfileHeader";
import { toast } from "react-toastify";
import TableBlock from "../Common/Table/TableBlock";
import { isSuperAdminLoggedIn } from "../../Services/userService";
import { deleteBrand, getBrandById } from "../../Services/brandsService";
import PageDetailsBlock from "../Common/PageDetailsBlock";
import { getAdsOfBrand } from "../../Services/adsService";
import { commonAdsTableHeaders } from "../Ads/Ads";

const BrandDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [data, setData] = useState<any>({});
  const [deleteDialog, setDeleteDialog] = useState<boolean>(false);
  const [ads, setAds] = useState<Array<any>>([]);
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    getDetails();
  }, []);

  const getDetails = async (onlyGetProject?: boolean) => {
    if (!id) navigate(allRoutes.BRANDS);

    setLoading(!onlyGetProject);
    try {
      const brandDetails = await getBrandById((id || "")?.toString());
      setData(brandDetails);

      const adsOfBrand: any = await getAdsOfBrand(id || "");
      setAds(adsOfBrand || []);
    } catch (error: any) {
      toast.error(error);
    }
    setLoading(false);
  };

  const openDeleteDialog = () => setDeleteDialog(true);
  const closeDeleteDialog = () => setDeleteDialog(false);

  const handleEdit = () =>
    navigate(allRoutes.EDIT_BRAND.replace(":id", (id || "")?.toString()));

  const handleDelete = async () => {
    try {
      const data: any = await deleteBrand(id || "");

      if (data === "Brand deleted successfully!") {
        toast.success(data);
        navigate(allRoutes.BRANDS);
      }
    } catch (error: any) {
      toast.error(error);
      if (error === "Brand with the given id was not found")
        navigate(allRoutes.BRANDS);
    }
  };

  const fields = [
    { text: "Name", key: "name" },
    { text: "Email", key: "email" },
    { text: "Address", key: "address" },
    { text: "Phone Number", key: "phone" },
  ];

  const headers = commonAdsTableHeaders;

  return (
    <PageLayout>
      <ProfileHeader
        data={data}
        userType='Brand'
        handleEdit={handleEdit}
        handleDelete={openDeleteDialog}
        disableDeleteButton={!!ads?.length}
        hideButtons={!isSuperAdminLoggedIn()}
        isLoading={loading}
      />

      <PageDetailsBlock
        data={data}
        fields={fields}
        showBottomDivider
        isLoading={loading}
      />

      <TableBlock
        heading={`Ads of ${data?.name || "Brand"}`}
        subHeading={`These are all the Ads of ${data?.name || "Brand"}`}
        tableData={ads}
        tableHeaders={headers}
        emptyStateMessage={`There are no ads generated by ${
          data?.name || "Brand"
        }`}
        detailsPagePath={allRoutes.VIEW_AD}
        isLoading={loading}
      />

      <DeleteDialog
        open={deleteDialog}
        onClose={closeDeleteDialog}
        userType='Brand'
        user={data}
        onDelete={handleDelete}
      />
    </PageLayout>
  );
};

export default BrandDetails;
